### ISSUE TITLE
Feature request - designate ALT/HDG

### ISSUE THREAD

**Issue by mgkid3310** [YannikH/itc_air#19]
The ALT/HDG mode seems to maintain ALT/HDG of when AP is initiated, but I wish if I could designate ALT/HDG to whatever value I like (simply think of commercial aircraft's AP). Setting HDG to a certain WP could be really great, too.

If needed, I could give some hand on that work

**Comment by YannikH** [comment]
Currently the AP is based on the modes available on the A-10C, though I am currently broadening the mod with features that apply beyond the A-10, and would happily expand the AP modes along with that.

Do you have any reference for which aircraft have an ALT/HDG mode where you input this data manually? I basically want to set up AP profiles configured to reflect various types of aircraft.

**Comment by mgkid3310** [comment]
I'm not sure about military aircrafts, but almost ALL commercial aircrafts have that feature.

ps. I'm working on and is pretty much complete with this feature, so you'll be albe to see the code on pull request in a few hours

**Comment by mgkid3310** [comment]
#20 I've finished with the code & created a pull request. Plz confirm if there's any issue with it, and if there isn't, it would be a pleasure to be accepted.

**Comment by YannikH** [comment]
I'm unable to do any arma related things this week, I'll have an in depth look at it and test it this Sunday.

**Comment by mgkid3310** [comment]
Sure, this is never an urgent issue, so just take your time XD

**Comment by YannikH** [comment]
I just merged and tested it, and I absolutely love it, thank you for the contribution.
